### ISSUE TITLE
Unable to specify partition size when using nvs_partition_generator

### ISSUE THREAD

**Issue by dermondbaer** [karawin/Ka-Radio32#69]
Hello,

I'm trying to create a custom I/O mapping but am stuck with the nvs_partition_gen.py script rejecting the size parameter. I'm using the latest script from espressif and am able to create a binary partition, although it's only 4KB (exactly 4096 Bytes) in size and the ESP won't boot after flashing it.

I noticed you have changed the aforementioned parameter a few times recently, so I thought you could maybe shed some light on this issue.

Although I guess it won't be of use I'll paste my configuration here, just in case: [custom.txt](https://github.com/karawin/Ka-Radio32/files/2612722/custom.txt)

Paul

**Comment by karawin** [comment]
Yes, the tool was unstable.
$ ./nvs_partition_generator.sh custom.csv
python C:/msys32/home/jp/esp/esp-idf/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py custom.csv build/custom.bin 8
done

[custom.zip](https://github.com/karawin/Ka-Radio32/files/2612948/custom.zip)

**Comment by dermondbaer** [comment]
Thanks for .zip - the tool is still not working for me (Ubuntu 18), but I'm using a HEX editor to fill up the last 4096 Bytes with FF's, so for me that's not a problem anymore.

This is out of context, but I'd rather not open a new issue just for this:
I'm not able to get my ILI9341 Display (MI0283QT-9A) to work although I'm pretty confident I wired and powered everything as needed - of course I'm using a different configuration from the above (standard_adb.bin). I saw the last commit (1.5 R1) states "lcdout was not working". Should it work with the new revision or could it still be a software issue? I guess you probably don't have a ILI9341 display to try it out? I wired everything except from the A0 pin, which in my understanding isn't needed.

Thank you for your efforts, you've created an impressive project!

**Comment by karawin** [comment]
Bad idea. May be it's time to update esp-idf

I own many ILI9341 fully tested in all configurations.
A0 is mandatory.
Please read https://github.com/karawin/Ka-Radio32/blob/master/HardwareConfig.md
A0 is P_LCD_A0 or default to PIN_LCD_A0	GPIO_NUM_14

lcdout was not working : lcdout is a simple tempo to clear the lcd when no new event to display.

**Comment by dermondbaer** [comment]
Indeed I used an old version of the esp-idf, when cloning the repository I didn't notice the `-b v3.1.1` option in the documentation: `git clone -b v3.1.1 --recursive https://github.com/espressif/esp-idf.git`

One more question regarding the LCD though:
In this [datasheet](https://download.mikroe.com/documents/datasheets/tft-320x240px-mi0283qt-9a-v1.3-datasheet.pdf), page 10 and 11, can you tell me at first glance which pin connects to A0 and which one to SCL (supposedly 36 and 37)? And the interface mode is `4-wire 8-bit data serial interface II`? I've tried both ways, but the screen stays white all the time.

Otherwise I'll just keep trying, I don't want to waste your time.

**Comment by karawin** [comment]
My 2.4 TFT SPI 240x320 pins:

bottom to top
VCC 3.3
GND 
CS    is PIN_LCD_CS	GPIO_NUM_13		//CS
RESET   PIN_LCD_RST	GPIO_NUM_2		//Reset RES RST or not used
DC   PIN_LCD_A0	GPIO_NUM_14		//A0 or D/C
SDI(MOSI)   PIN_NUM_MOSI GPIO_NUM_23	// Master Output, Slave Input   Named Data or SDA or D1 for oled
SCK   PIN_NUM_CLK  GPIO_NUM_18 	// Master clock  Named SCL or SCK or D0 for oled
LED  to 3.3 with or without a resistor

**Comment by dermondbaer** [comment]
All the other pins are clear to me, it's just the A0 zero pin that I can't assign to one on the lcd - I thought it's possible you have the same model.

Probably I'll try to get another display - can you recommend a bigger one, maybe around 2 or 3 inches in size? I'm only seeing the small OLED displays (0.91", 1.3", ...) that are widely available on ebay etc.

**Comment by karawin** [comment]
**A0** also named **DC** or D/C is used to switch  from command data to pure data on MOSI

2.8'' is the biggest resolution 240x320  adapted for the software.
May be a future evolution.

**Comment by karawin** [comment]
https://www.dropbox.com/s/bexdntd3v04rlu2/2018-11-26%2009.13.11.jpg?dl=0
